---

- hosts: localhost
  gather_facts: true
  tasks:
      # install MySQL repo
      - name: Install mysql-repo
        ansible.builtin.yum:
          name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      # install MySQL Server
      - name: Install mysql-server
        ansible.builtin.yum:
          name: mysql-server
      # enable MySQL deamon
      - name: Enable Mysql systemd
        ansible.builtin.systemd:
          name: mysqld
          enabled: true
          masked: no
      # Run MySQL Server. 
      - name: Start Mysql Service
        ansible.builtin.systemd:
          name: mysqld
          state: started